name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Deploy to Surge
      run:  npm install --global surge
    - name: Deploy to Surge again
      run:  surge ./ grumpy-room.surge.sh --token ${{ secrets.SURGE_TOKEN }}
